import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // ================================
  // 🧠 ROS 2 – Nervous System
  // ================================
  ros2NervousSystemSidebar: [
    {
      type: 'category',
      label: '🧠 ROS 2 Nervous System',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ros2-nervous-system',
        },
      ],
    },
  ],

  // ================================
  // 🌐 Digital Twin – Gazebo & Unity
  // ================================
  digitalTwinGazeboUnitySidebar: [
    {
      type: 'category',
      label: '🌐 Digital Twin (Gazebo & Unity)',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'digital-twin-gazebo-unity',
        },
      ],
    },
  ],

  // ================================
  // 🧬 NVIDIA Isaac – AI Robot Brain
  // ================================
  nvidiaIsaacSidebar: [
    {
      type: 'category',
      label: '🧬 AI Robot Brain (NVIDIA Isaac)',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nvidia-isaac',
        },
      ],
    },
  ],

  // ================================
  // 👁️ Vision-Language-Action (VLA)
  // ================================
  vlaHumanoidSidebar: [
    {
      type: 'category',
      label: '👁️ Vision–Language–Action (VLA)',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'vla-humanoid',
        },
      ],
    },
  ],

  // ================================
  // 📘 Master Book Index (Optional Future Expansion)
  // ================================
  /*
  masterBookIndex: [
    {
      type: 'category',
      label: '📘 AI-Humanoid Engineering Master Index',
      collapsible: true,
      collapsed: true,
      items: [
        'intro',
        {
          type: 'category',
          label: 'Foundations',
          items: ['foundation/ai-basics', 'foundation/robotics-basics'],
        },
        {
          type: 'category',
          label: 'Advanced Systems',
          items: ['advanced/autonomy', 'advanced/multi-agent'],
        },
      ],
    },
  ],
  */
};

export default sidebars;
